## valid uuid = 6cdd799c-c886-47b7-8010-3adb97d73b83

 
### 
# @name createCategory
POST http://localhost:3000/categories
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Category 1",
  "description": "Description 1"
}

###

@categoryId = {{createCategory.response.body.data.id}}

###
GET http://localhost:3000/categories
Authorization: Bearer {{jwtToken}}

###
GET http://localhost:3000/categories/8f4b7b9c-3f7a-4b6c-8b0c-1c9c5b8b9b6a
Authorization: Bearer {{jwtToken}}


### 
# @name createGenre
POST http://localhost:3000/genres
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Genre 1",
    "categories_id": [
      "{{categoryId}}"
    ]
}

###

@genreId = {{createGenre.response.body.data.id}}

###
# @name createCastMember
POST http://localhost:3000/cast-members
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Cast Member 1",
  "type": 1
}

###

@castMemberId = {{createCastMember.response.body.data.id}}

###


### Verificar Criações
GET http://localhost:3000/categories/{{categoryId}}
###
GET http://localhost:3000/genres/{{genreId}}
###
GET http://localhost:3000/cast-members/{{castMemberId}}


###

# @name createVideo
POST http://localhost:3000/videos
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "Vídeo Teste",
  "description": "Descrição do vídeo teste",
  "year_launched": 2024,
  "is_opened": false,
  "rating": "L",
  "duration": 90,
  "categories_id": ["{{categoryId}}"],
  "genres_id": ["{{genreId}}"],
  "cast_members_id": ["{{castMemberId}}"]
}

###

@videoId = {{createVideo.response.body.data.id}}

###

# @name updateVideo
PATCH http://localhost:3000/videos/{{videoId}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "Video Teste Atualizado",
  "description": "Descrição do video teste atualizado",
  "year_launched": 2024,
  "is_opened": false,
  "rating": "L",
  "duration": 90,
  "categories_id": ["{{categoryId}}"],
  "genres_id": ["{{genreId}}"],
  "cast_members_id": ["{{castMemberId}}"]
}

###
# @name updateVideo

PATCH http://localhost:3000/videos/{{videoId}}
Authorization: Bearer {{jwtToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary1234

------WebKitFormBoundary1234
Content-Disposition: form-data; name="video"; filename="video.mp4"
Content-Type: video/mp4

< ./package.json
# ------WebKitFormBoundary1234
# Content-Disposition: form-data; name="video"; filename="video.mp4"
# Content-Type: video/mp4

# < ./package.json
------WebKitFormBoundary1234--
 

###
GET http://localhost:3000/fake-event
Authorization: Bearer {{jwtToken}}
###
GET http://localhost:3000/rabbitmq-fake
Authorization: Bearer {{jwtToken}}


###

# @name Keycloak
POST http://host.docker.internal:8080/realms/codeflix/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=admin@user.com
&password=secret
&grant_type=password
&client_id=codeflix-admin-frontend

# Up keycloack container manually
# docker compose -f docker-compose-keycloak.yaml up

##
### configuração do openid connect server
GET http://host.docker.internal:8080/realms/codeflix/.well-known/openid-configuration

### Certificados
GET http://host.docker.internal:8080/realms/codeflix/protocol/openid-connect/certs 


###
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@user.com",
  "password": "secret"
}
###

@jwtToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiYWRtaW4tY2F0YWxvZyJdfSwiaWF0IjoxNzQ3NDA2OTIzLCJleHAiOjE3NDc0OTMzMjN9.WnCUexn7bmQIlTqs80ZiHNWdVhE78WV5x1onCBATCRuUeSKPxtPgdEs-j5Ek6x8-oAAJrPgekx9Pu3H_xqTWKUz0XImVgOynaYGNc2K-Up5pukpaq56aBjMX_6O5cwu0vJfyKzr4JUmcGOBGpzEezEBUFDev-V2MMlvzyCicvEHF9ST6AMbWn9-T0dMI-HibJYMNb7BW2y38R6wMaoW4MpifmiOxEbWIL8h7RYiNcLWncZKeoaUt6tNK45_g0pY9-5spIykwHrpNUzlfGDNANm_lgHR3Cujz5MIIUv55KZHxF-XKjA_fhDLXWiL-QC-SOyITRxtpLAjjiGJuu24Npg

###
GET http://localhost:3000/auth/protected
Content-Type: application/json
Authorization: Bearer {{jwtToken}}
 

