version: '3'

services:
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db: 
    image: mysql:8.3.0
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    security_opt:
      - seccomp:unconfined